const Parser = require('acorn')
const codeGenerator = require('./codeGenerator')
const jsrmsConfig = require('../jsrms.config.json')
const fs = require('fs')
const { format } = require('date-fns')
const utils = require('./utils')
const homedir = require('os').homedir()
const pathToSave = jsrmsConfig.outputFolderPath || homedir + '/Documents/My Games/Age of Empires 3/RM3'

const file = fs.readFileSync(jsrmsConfig.sourceFile)
const ast = Parser.parse(file, { ecmaVersion: 2020 })
const codeGenerated = codeGenerator(ast)
const pathXS = pathToSave + '\\' + jsrmsConfig.mapName + '.xs'
const pathXML = pathToSave + '\\' + jsrmsConfig.mapName + '.xml'

const result = `
/*
Map file generated by jsrms tool : https://github.com/PierreCapo/jsrms
Generation Date: ${format(Date.now(), 'EEE MMM dd HH:mm:ss xx yyyy')}
${jsrmsConfig.authorName && 'Author: ' + jsrmsConfig.authorName}
*/
/*
include "mercenaries.xs";
include "ypAsianInclude.xs";
include "ypKOTHInclude.xs";

int i = 0;
int j = 0;
int k = 0;

void main (void) {

${codeGenerated}

}
`

if (!fs.existsSync(pathToSave)) {
    if (!jsrmsConfig.outputFolderPath) {
        throw Error(`The jsrms compiler is unable to find the following path used by default to save maps in your machine: ${pathToSave} 
        Please edit the jsrms.config.json file to specify the outputFolderPath where you want the map file generated to be placed.
        Check the README file for more information on how to specify a custom path.
        `)
    } else {
        throw Error(`The jsrms compiler is unable to find the following path that you mentioned in the jsrms.config.json file to save maps in your machine: ${pathToSave} 
        Please verify you haven't written a typo in the outputFolderPath key.
        Check the README file for more information on how to specify a custom path.
        `)
    }
}

fs.writeFileSync(pathXS, result)
fs.writeFileSync(pathXML, utils.generateXml(jsrmsConfig.mapDisplayName))
console.log(format(Date.now(), 'HH:mm:ss') + ' - Map file has been generated at : ' + pathXS)
