const Parser = require('acorn');
const codeGenerator = require('./codeGenerator');
const jsrmsConfig = require('../jsrms.config.json');
const fs = require('fs');
const { format } = require('date-fns');
const utils = require('./utils');
const homedir = require('os').homedir();
const pathToSave = jsrmsConfig.outputFolderPath || homedir + '/Documents/My Games/Age of Empires 3/RM3';

const file = fs.readFileSync(jsrmsConfig.sourceFile);
const ast = Parser.parse(file);
const codeGenerated = codeGenerator(ast);
const pathXS = pathToSave + '\\' + jsrmsConfig.mapName + '.xs';
const pathXML = pathToSave + '\\' + jsrmsConfig.mapName + '.xml';

const result = `
/*
Map file generated by jsrms tool : https://github.com/PierreCapo/jsrms
Generation Date: ${format(Date.now(), 'EEE MMM dd HH:mm:ss xx yyyy')}
${jsrmsConfig.authorName && 'Author: ' + jsrmsConfig.authorName}
*/

include "mercenaries.xs";
include "ypAsianInclude.xs";
include "ypKOTHInclude.xs";

int i = 0;
int j = 0;
int k = 0;

void main (void) {

${codeGenerated}

}
`;

fs.writeFileSync(pathXS, result);
fs.writeFileSync(pathXML, utils.generateXml(jsrmsConfig.mapDisplayName));
console.log(format(Date.now(), 'HH:mm:ss') + ' - Map file has been generated at : ' + pathXS);
