const fs = require('fs');

const getTypeOf = (value) => {
    const valueType = typeof value;

    switch (valueType) {
        case 'string':
            return 'string';
        case 'boolean':
            return 'bool';
        case 'number':
            if (Number.isInteger(valueType)) {
                return 'int';
            } else {
                return 'float';
            }
        default:
            throw new TypeError('Can not determine the type of ' + value);
    }
};

const listOfFunctionWithUUID = [
    'rmCreateTradeRouteDistanceConstraint',
    'rmCreateCornerConstraint',
    'rmCreateTerrainMaxDistanceConstraint',
    'rmCreateTerrainDistanceConstraint',
    'rmCreateTypeDistanceConstraint',
    'rmCreateClassDistanceConstraint',
    'rmCreateCliffRampMaxDistanceConstraint',
    'rmCreateCliffRampDistanceConstraint',
    'rmCreateCliffRampConstraint',
    'rmCreateCliffEdgeMaxDistanceConstraint',
    'rmCreateCliffEdgeDistanceConstraint',
    'rmCreateCliffEdgeConstraint',
    'rmCreateEdgeMaxDistanceConstraint',
    'rmCreateEdgeDistanceConstraint',
    'rmCreateEdgeConstraint',
    'rmCreateAreaMaxDistanceConstraint',
    'rmCreateAreaDistanceConstraint',
    'rmCreateAreaConstraint',
    'rmCreateAreaOverlapConstraint',
    'rmCreatePieConstraint',
    'rmCreateArea',
    'rmCreateObjectDef',
];

let interfaceFile = fs.readFileSync('./interface.d.ts', 'utf8');
functionsTyped = interfaceFile.replace(/^((?!declare const).)*/gm, '');
functionsTyped = functionsTyped.replace(/declare const/gm, '');
functionsTyped = functionsTyped.replace(/\(.*\>/gm, '');
functionsTyped = functionsTyped.replace(/\n/g, '');
functionsTyped = functionsTyped.split(';');
functionsTyped = functionsTyped.reduce((acc, rmFunction) => {
    rmFunction = rmFunction.replace(/\s/g, '');
    let [key, value] = rmFunction.split(':');
    value = value === 'Area' || value === 'Constraint' || value === 'River' ? 'int' : value;
    value = value === 'Vector' ? 'vector' : value;
    value = value === 'boolean' ? 'bool' : value;
    value = value === 'integer' ? 'int' : value;
    return { ...acc, [key]: value };
}, {});

getTypeOfReturnedValue = (functionName) => {
    return functionsTyped[functionName];
};

const generateXml = (displayName) => `<?xml version = "1.0" encoding = "UTF-8"?>
<mapinfo details = "" imagepath = "" displayName = "${displayName}" cannotReplace = ""
         loadDetails="" loadBackground="">
   <loadss></loadss>
   <loadss></loadss>
   <loadss></loadss>
</mapinfo>`;

const identifierMapper = {
    GREAT_PLAINS_DEFAULT: 'great_plains\\default',
    ANDES_GROUND07_AND: 'andes\\ground07_and',
    ANDES_GROUND08_AND: 'andes\\ground08_and',
    ANDES_GROUND09_AND: 'andes\\ground09_and',
    ANDES_GROUND10_AND: 'andes\\ground10_and',
    ANDES_GROUND11_AND: 'andes\\ground11_and',
    ANDES_GROUND12_AND: 'andes\\ground12_and',
    ANDES_GROUND14_AND: 'andes\\ground14_and',
    ANDES_GROUND16_AND: 'andes\\ground16_and',
    ANDES_GROUND17_AND: 'andes\\ground17_and',
    ANDES_GROUND18_AND: 'andes\\ground18_and',
    ANDES_GROUND22_AND: 'andes\\ground22_and',
    ANDES_GROUND25_AND: 'andes\\ground25_and',
    AMAZON_GROUND1_AMA: 'amazon\\ground1_ama',
    AMAZON_GROUND2_AMA: 'amazon\\ground2_ama',
    AMAZON_GROUND3_AMA: 'amazon\\ground3_ama',
    AMAZON_GROUND4_AMA: 'amazon\\ground4_ama',
    AMAZON_GROUND5_AMA: 'amazon\\ground5_ama',
    AMAZON_GROUNDFOREST_AMA: 'amazon\\groundforest_ama',
    AMAZON_CLIFF_TOP1_AMA: 'amazon\\cliff_top1_ama',
    AMAZON_RIVER3_AM: 'amazon\\river3_am',
    ARAUCANIA_GROUND12_ARA: 'araucania\\ground12_ara',
    ARAUCANIA_GROUND07_ARA: 'araucania\\ground07_ara',
    ARAUCANIA_GROUND09_ARA: 'araucania\\ground09_ara',
    ARAUCANIA_GROUND_GRASS1_ARA: 'araucania\\ground_grass1_ara',
    ARAUCANIA_GROUND08_ARA: 'araucania\\ground08_ara',
    ARAUCANIA_GROUND10_ARA: 'araucania\\ground10_ara',
    ARAUCANIA_GROUND_GRASS2_ARA: 'araucania\\ground_grass2_ara',
    ARAUCANIA_GROUND_GRASS3_ARA: 'araucania\\ground_grass3_ara',
    ARAUCANIA_GROUND11_ARA: 'araucania\\ground11_ara',
    ARAUCANIA_GROUNDFORESTCENTRAL: 'araucania\\groundforestcentral',
    ARAUCANIA_GROUND_DIRT1_ARA: 'araucania\\ground_dirt1_ara',
    ARAUCANIA_GROUND_DIRT2_ARA: 'araucania\\ground_dirt2_ara',
    ARAUCANIA_GROUND_DIRT3_ARA: 'araucania\\ground_dirt3_ara',
    ARAUCANIA_CLIFF_COAST2_ARA: 'araucania\\cliff_coast2_ara',
    ARAUCANIA_CLIFF_COAST3_ARA: 'araucania\\cliff_coast3_ara',
    ARAUCANIA_CLIFF_DIRT_SNOW_ARA: 'araucania\\cliff_dirt_snow_ara',
    ARAUCANIA_CLIFF_COAST_ARA: 'araucania\\cliff_coast_ara',
    ARAUCANIA_CLIFF_DIRT2_ARA: 'araucania\\cliff_dirt2_ara',
    ARAUCANIA_CLIFF_DIRT_ARA: 'araucania\\cliff_dirt_ara',
    ARAUCANIA_GROUND_SNOW1_ARA: 'araucania\\ground_snow1_ara',
    ARAUCANIA_GROUND_SNOW2_ARA: 'araucania\\ground_snow2_ara',
    ARAUCANIA_GROUND_SNOW3_ARA: 'araucania\\ground_snow3_ara',
    ARAUCANIA_GROUND_SNOW4_ARA: 'araucania\\ground_snow4_ara',
    ARAUCANIA_GROUND_SNOW5_ARA: 'araucania\\ground_snow5_ara',
    BAYOU_GROUND1_BAY: 'bayou\\ground1_bay',
    BAYOU_GROUND2_BAY: 'bayou\\ground2_bay',
    BAYOU_GROUND3_BAY: 'bayou\\ground3_bay',
    BAYOU_GROUND5_BAY: 'bayou\\ground5_bay',
    BAYOU_GROUND6_BAY: 'bayou\\ground6_bay',
    BAYOU_CLIFF_TOP1_BAY: 'bayou\\cliff_top1_bay',
    BAYOU_GROUNDFOREST_BAY: 'bayou\\groundforest_bay',
    CALIFORNIA_GROUNDFOREST2_CAL: 'california\\groundforest2_cal',
    CALIFORNIA_GROUND5_CAL: 'california\\ground5_cal',
    CALIFORNIA_GROUND6_CAL: 'california\\ground6_cal',
    CALIFORNIA_GROUND7_CAL: 'california\\ground7_cal',
    CALIFORNIA_GROUND8_CAL: 'california\\ground8_cal',
    CALIFORNIA_GROUND9_CAL: 'california\\ground9_cal',
    CALIFORNIA_FAKECALIFGRASSMIX_CAL: 'california\\fakecalifgrassmix_cal',
    CALIFORNIA_FAKECALIFGRASSMIX2_CAL: 'california\\fakecalifgrassmix2_cal',
    CALIFORNIA_DESERT2_CAL: 'california\\desert2_cal',
    CALIFORNIA_DESERT3_CAL: 'california\\desert3_cal',
    CALIFORNIA_DESERT4_CAL: 'california\\desert4_cal',
    CALIFORNIA_DESERT5_CAL: 'california\\desert5_cal',
    CALIFORNIA_DESERT6_CAL: 'california\\desert6_cal',
    CALIFORNIA_GROUND_CLIFFTOP_CAL: 'california\\ground_clifftop_cal',
    CALIFORNIA_MADRONE_FOREST_CAL: 'california\\madrone_forest_cal',
    CALIFORNIA_MADRONEFOREST2_CAL: 'california\\madroneforest2_cal',
    CALIFORNIA_GROUNDFOREST_CAL: 'california\\groundforest_cal',
    CARIBBEAN_GROUND1_CRB: 'caribbean\\ground1_crb',
    CARIBBEAN_GROUND2_CRB: 'caribbean\\ground2_crb',
    CARIBBEAN_GROUND3_CRB: 'caribbean\\ground3_crb',
    CARIBBEAN_GROUND4_CRB: 'caribbean\\ground4_crb',
    CARIBBEAN_GROUND6_CRB: 'caribbean\\ground6_crb',
    CARIBBEAN_GROUND7_CRB: 'caribbean\\ground7_crb',
    CARIBBEAN_CLIFF_TOP1_CRB: 'caribbean\\cliff_top1_crb',
    CARIBBEAN_GROUNDFOREST_CRB: 'caribbean\\groundforest_crb',
    CARIBBEAN_SEAFLOOR_CORAL0_CRB: 'caribbean\\seafloor_coral0_crb',
    CARIBBEAN_SEAFLOOR_CORAL1_CRB: 'caribbean\\seafloor_coral1_crb',
    CARIBBEAN_SEAFLOOR_CORAL2_CRB: 'caribbean\\seafloor_coral2_crb',
    CARIBBEAN_SEAFLOOR_CORAL3_CRB: 'caribbean\\seafloor_coral3_crb',
    CARIBBEAN_SEAFLOOR_CORAL4_CRB: 'caribbean\\seafloor_coral4_crb',
    CAROLINAS_GROUND_GRASS1_CAR: 'carolinas\\ground_grass1_car',
    CAROLINAS_GROUND_GRASS2_CAR: 'carolinas\\ground_grass2_car',
    CAROLINAS_GROUND_GRASS3_CAR: 'carolinas\\ground_grass3_car',
    CAROLINAS_GROUND_GRASS4_CAR: 'carolinas\\ground_grass4_car',
    CAROLINAS_CLIFF_TOP1_CAR: 'carolinas\\cliff_top1_car',
    CAROLINAS_GROUND_MARSH1_CAR: 'carolinas\\ground_marsh1_car',
    CAROLINAS_GROUND_MARSH2_CAR: 'carolinas\\ground_marsh2_car',
    CAROLINAS_GROUND_MARSH3_CAR: 'carolinas\\ground_marsh3_car',
    CAROLINAS_GROUNDFOREST_CAR: 'carolinas\\groundforest_car',
    CAROLINAS_COBBLESTONE: 'carolinas\\cobblestone',
    CAROLINAS_BLACKMAP: 'carolinas\\blackmap',
    CAVE_CAVE_GROUND1: 'cave\\cave_ground1',
    CAVE_CAVE_GROUND2: 'cave\\cave_ground2',
    CAVE_CAVE_GROUND3: 'cave\\cave_ground3',
    CAVE_CAVE_GROUND4: 'cave\\cave_ground4',
    GREAT_LAKES_GROUND_SNOW1_GL: 'great_lakes\\ground_snow1_gl',
    GREAT_LAKES_GROUND_SNOW2_GL: 'great_lakes\\ground_snow2_gl',
    GREAT_LAKES_GROUND_SNOW3_GL: 'great_lakes\\ground_snow3_gl',
    GREAT_LAKES_GROUND_SNOW4_GL: 'great_lakes\\ground_snow4_gl',
    GREAT_LAKES_GROUND_SNOW5_GL: 'great_lakes\\ground_snow5_gl',
    GREAT_LAKES_GROUND_GRASS1_GL: 'great_lakes\\ground_grass1_gl',
    GREAT_LAKES_GROUND_GRASS2_GL: 'great_lakes\\ground_grass2_gl',
    GREAT_LAKES_GROUND_GRASS3_GL: 'great_lakes\\ground_grass3_gl',
    GREAT_LAKES_GROUND_GRASS4_GL: 'great_lakes\\ground_grass4_gl',
    GREAT_LAKES_GROUND_GRASS5_GL: 'great_lakes\\ground_grass5_gl',
    GREAT_LAKES_GROUNDFOREST_GL: 'great_lakes\\groundforest_gl',
    GREAT_LAKES_GROUNDFOREST_SNOW_GL: 'great_lakes\\groundforest_snow_gl',
    GREAT_PLAINS_GROUND1_GP: 'great_plains\\ground1_gp',
    GREAT_PLAINS_GROUND2_GP: 'great_plains\\ground2_gp',
    GREAT_PLAINS_GROUND3_GP: 'great_plains\\ground3_gp',
    GREAT_PLAINS_GROUND4_GP: 'great_plains\\ground4_gp',
    GREAT_PLAINS_GROUND5_GP: 'great_plains\\ground5_gp',
    GREAT_PLAINS_GROUND6_GP: 'great_plains\\ground6_gp',
    GREAT_PLAINS_GROUND7_GP: 'great_plains\\ground7_gp',
    GREAT_PLAINS_GROUND8_GP: 'great_plains\\ground8_gp',
    GREAT_PLAINS_GROUNDFOREST_GP: 'great_plains\\groundforest_gp',
    GREAT_PLAINS_PONDBANK_GP: 'great_plains\\pondbank_gp',
    NEW_ENGLAND_GROUND1_NE: 'new_england\\ground1_ne',
    NEW_ENGLAND_GROUND2_NE: 'new_england\\ground2_ne',
    NEW_ENGLAND_GROUND3_NE: 'new_england\\ground3_ne',
    NEW_ENGLAND_GROUND4_NE: 'new_england\\ground4_ne',
    NEW_ENGLAND_GROUND5_NE: 'new_england\\ground5_ne',
    NEW_ENGLAND_CLIFF_TOP_NE: 'new_england\\cliff_top_ne',
    NEW_ENGLAND_CLIFF_EDGE_NE: 'new_england\\cliff_edge_ne',
    NEW_ENGLAND_CLIFF_SIDE_NE: 'new_england\\cliff_side_ne',
    NEW_ENGLAND_GROUND2_CLIFF_NE: 'new_england\\ground2_cliff_ne',
    NEW_ENGLAND_CLIFF_INLAND_TOP_NE: 'new_england\\cliff_inland_top_ne',
    NEW_ENGLAND_CLIFF_INLAND_EDGE_NE: 'new_england\\cliff_inland_edge_ne',
    NEW_ENGLAND_CLIFF_INLAND_SIDE_NE: 'new_england\\cliff_inland_side_ne',
    NEW_ENGLAND_RIVER1_NE: 'new_england\\river1_ne',
    NEW_ENGLAND_GROUNDFOREST_NE: 'new_england\\groundforest_ne',
    NWTERRITORY_GROUND_GRASS1_NWT: 'nwterritory\\ground_grass1_nwt',
    NWTERRITORY_GROUND_GRASS1A_NWT: 'nwterritory\\ground_grass1a_nwt',
    NWTERRITORY_GROUND_GRASS2_NWT: 'nwterritory\\ground_grass2_nwt',
    NWTERRITORY_GROUND_GRASS3_NWT: 'nwterritory\\ground_grass3_nwt',
    NWTERRITORY_GROUND_GRASS5_NWT: 'nwterritory\\ground_grass5_nwt',
    NWTERRITORY_GROUND_SHORELINE3_NWT: 'nwterritory\\ground_shoreline3_nwt',
    NWTERRITORY_GROUND_RIVERBED_NWT: 'nwterritory\\ground_riverbed_nwt',
    NWTERRITORY_GROUND_RIVERBED2_NWT: 'nwterritory\\ground_riverbed2_nwt',
    PAMPAS_GROUND1_PAM: 'pampas\\ground1_pam',
    PAMPAS_GROUND2_PAM: 'pampas\\ground2_pam',
    PAMPAS_GROUND3_PAM: 'pampas\\ground3_pam',
    PAMPAS_GROUND4_PAM: 'pampas\\ground4_pam',
    PAMPAS_GROUND5_PAM: 'pampas\\ground5_pam',
    PAMPAS_GROUND6_PAM: 'pampas\\ground6_pam',
    PAMPAS_GROUNDFOREST_PAM: 'pampas\\groundforest_pam',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_A: 'painteddesert\\pd_ground_diffuse_a',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_B: 'painteddesert\\pd_ground_diffuse_b',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_C: 'painteddesert\\pd_ground_diffuse_c',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_D: 'painteddesert\\pd_ground_diffuse_d',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_E: 'painteddesert\\pd_ground_diffuse_e',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_F: 'painteddesert\\pd_ground_diffuse_f',
    PAINTEDDESERT_PD_CLIFF_DIFFUSE_A: 'painteddesert\\pd_cliff_diffuse_a',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_G: 'painteddesert\\pd_ground_diffuse_g',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_H: 'painteddesert\\pd_ground_diffuse_h',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_I: 'painteddesert\\pd_ground_diffuse_i',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_J: 'painteddesert\\pd_ground_diffuse_j',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_K: 'painteddesert\\pd_ground_diffuse_k',
    PAINTEDDESERT_PD_GROUND_DIFFUSE_L: 'painteddesert\\pd_ground_diffuse_l',
    PATAGONIA_GROUND_GRASS1_PAT: 'patagonia\\ground_grass1_pat',
    PATAGONIA_GROUND_GRASS2_PAT: 'patagonia\\ground_grass2_pat',
    PATAGONIA_GROUND_GRASS3_PAT: 'patagonia\\ground_grass3_pat',
    PATAGONIA_GROUND_DIRT1_PAT: 'patagonia\\ground_dirt1_pat',
    PATAGONIA_GROUND_DIRT2_PAT: 'patagonia\\ground_dirt2_pat',
    PATAGONIA_GROUND_DIRT3_PAT: 'patagonia\\ground_dirt3_pat',
    PATAGONIA_GROUND_SNOW1_PAT: 'patagonia\\ground_snow1_pat',
    PATAGONIA_GROUND_SNOW2_PAT: 'patagonia\\ground_snow2_pat',
    PATAGONIA_GROUND_SNOW3_PAT: 'patagonia\\ground_snow3_pat',
    PATAGONIA_GROUNDFOREST_PAT: 'patagonia\\groundforest_pat',
    PATAGONIA_GROUNDFOREST_SNOW_PAT: 'patagonia\\groundforest_snow_pat',
    PATAGONIA_GROUND_CLIFFTOP_PAT: 'patagonia\\ground_clifftop_pat',
    ROCKIES_GROUND1_ROC: 'rockies\\ground1_roc',
    ROCKIES_GROUND2_ROC: 'rockies\\ground2_roc',
    ROCKIES_GROUND3_ROC: 'rockies\\ground3_roc',
    ROCKIES_GROUND4_ROC: 'rockies\\ground4_roc',
    ROCKIES_GROUND5_ROC: 'rockies\\ground5_roc',
    ROCKIES_GROUNDSNOW1_ROC: 'rockies\\groundsnow1_roc',
    ROCKIES_GROUNDSNOW2_ROC: 'rockies\\groundsnow2_roc',
    ROCKIES_GROUNDSNOW3_ROC: 'rockies\\groundsnow3_roc',
    ROCKIES_GROUNDSNOW4_ROC: 'rockies\\groundsnow4_roc',
    ROCKIES_GROUNDSNOW5_ROC: 'rockies\\groundsnow5_roc',
    ROCKIES_GROUNDSNOW6_ROC: 'rockies\\groundsnow6_roc',
    ROCKIES_GROUNDSNOW7_ROC: 'rockies\\groundsnow7_roc',
    ROCKIES_GROUNDSNOW8_ROC: 'rockies\\groundsnow8_roc',
    ROCKIES_GROUNDFORESTSNOW_ROC: 'rockies\\groundforestsnow_roc',
    ROCKIES_GROUNDFOREST_ROC: 'rockies\\groundforest_roc',
    SAGUENAY_GROUND1_SAG: 'saguenay\\ground1_sag',
    SAGUENAY_GROUND2_SAG: 'saguenay\\ground2_sag',
    SAGUENAY_GROUND3_SAG: 'saguenay\\ground3_sag',
    SAGUENAY_GROUND4_SAG: 'saguenay\\ground4_sag',
    SAGUENAY_GROUND5_SAG: 'saguenay\\ground5_sag',
    SAGUENAY_GROUND6_SAG: 'saguenay\\ground6_sag',
    SAGUENAY_RIVER1_SAG: 'saguenay\\river1_sag',
    SAGUENAY_GROUNDFOREST_SAG: 'saguenay\\groundforest_sag',
    SONORA_GROUND1_SON: 'sonora\\ground1_son',
    SONORA_GROUND2_SON: 'sonora\\ground2_son',
    SONORA_GROUND3_SON: 'sonora\\ground3_son',
    SONORA_GROUND4_SON: 'sonora\\ground4_son',
    SONORA_GROUND5_SON: 'sonora\\ground5_son',
    SONORA_GROUND6_SON: 'sonora\\ground6_son',
    SONORA_GROUND7_SON: 'sonora\\ground7_son',
    SONORA_GROUND1CLIFFTOP_SON: 'sonora\\ground1clifftop_son',
    SONORA_CLIFF_EDGE_SON: 'sonora\\cliff_edge_son',
    SONORA_GROUNDFOREST_SON: 'sonora\\groundforest_son',
    TEXAS_GROUND1_TEX: 'texas\\ground1_tex',
    TEXAS_GROUND2_TEX: 'texas\\ground2_tex',
    TEXAS_GROUND3_TEX: 'texas\\ground3_tex',
    TEXAS_GROUND4_TEX: 'texas\\ground4_tex',
    TEXAS_GROUND5_TEX: 'texas\\ground5_tex',
    TEXAS_GROUND6_TEX: 'texas\\ground6_tex',
    TEXAS_CLIFF_EDGE_TEX: 'texas\\cliff_edge_tex',
    TEXAS_CLIFF_TOP_TEX: 'texas\\cliff_top_tex',
    TEXAS_CLIFF_TOP_GRASS_TEX: 'texas\\cliff_top_grass_tex',
    TEXAS_RIVER1_TEX: 'texas\\river1_tex',
    TEXAS_RIVER2_TEX: 'texas\\river2_tex',
    TEXAS_GROUNDFOREST_TEX: 'texas\\groundforest_tex',
    TEXAS_GROUNDFORESTDIRT_TEX: 'texas\\groundforestdirt_tex',
    YUKON_GROUND1_YUK: 'yukon\\ground1_yuk',
    YUKON_GROUND2_YUK: 'yukon\\ground2_yuk',
    YUKON_GROUND4_YUK: 'yukon\\ground4_yuk',
    YUKON_GROUND5_YUK: 'yukon\\ground5_yuk',
    YUKON_GROUND6_YUK: 'yukon\\ground6_yuk',
    YUKON_GROUND7_YUK: 'yukon\\ground7_yuk',
    YUKON_GROUND8_YUK: 'yukon\\ground8_yuk',
    YUKON_GROUND9_YUK: 'yukon\\ground9_yuk',
    YUKON_GROUND11_YUK: 'yukon\\ground11_yuk',
    YUKON_GROUND10_YUK: 'yukon\\ground10_yuk',
    YUKON_GROUNDFOREST_YUK: 'yukon\\groundforest_yuk',
    YUKON_GROUNDFORESTSNOW_YUK: 'yukon\\groundforestsnow_yuk',
    YUKON_GROUND3_YUK: 'yukon\\ground3_yuk',
    YUKON_GROUND3X_YUK: 'yukon\\ground3x_yuk',
    SPC_SCORCHED01: 'spc\\scorched01',
    SPC_SCORCHED02: 'spc\\scorched02',
    SPC_SCORCHED03: 'spc\\scorched03',
    SPC_SCORCHED04: 'spc\\scorched04',
    PROPS_EAST_COLONY: 'props\\east_colony',
    PROPS_EAST_COLONY1: 'props\\east_colony1',
    PROPS_EAST_COLONY2: 'props\\east_colony2',
    PATAGONIA_GROUND_GLACIER_PAT: 'patagonia\\ground_glacier_pat',
    ROCKIES_CLIFFTOP_ROC: 'rockies\\clifftop_roc',
    CAROLINAS_UNDERWATER1: 'carolinas\\Underwater1',
    CAROLINAS_UNDERWATER2: 'carolinas\\Underwater2',
    CAROLINAS_UNDERWATER3: 'carolinas\\Underwater3',
    NEW_ENGLAND_UNDERWATER1_NE: 'new_england\\Underwater1_ne',
    NEW_ENGLAND_UNDERWATER2_NE: 'new_england\\Underwater2_ne',
    SAGUENAY_UNDERWATER1_SAG: 'saguenay\\underwater1_sag',
    SAGUENAY_UNDERWATER2_SAG: 'saguenay\\underwater2_sag',
    SAGUENAY_UNDERWATER3_SAG: 'saguenay\\underwater3_sag',
    AMAZON_RIVER1_AM: 'amazon\\river1_am',
    AMAZON_RIVER2_AM: 'amazon\\river2_am',
    ARAUCANIA_GROUNDSHORE1_ARA: 'araucania\\groundshore1_ara',
    ARAUCANIA_GROUNDSHORE5_ARA: 'araucania\\groundshore5_ara',
    ARAUCANIA_GROUNDSHORE8_ARA: 'araucania\\groundshore8_ara',
    CALIFORNIA_GROUNDSHORE1_CAL: 'california\\groundshore1_cal',
    CALIFORNIA_GROUNDSHORE2_CAL: 'california\\groundshore2_cal',
    CALIFORNIA_GROUNDSHORE3B_CAL: 'california\\groundshore3b_cal',
    CALIFORNIA_GROUNDSHORE3C_CAL: 'california\\groundshore3c_cal',
    CALIFORNIA_GROUNDSHORE3D_CAL: 'california\\groundshore3d_cal',
    CALIFORNIA_GROUNDSHORE4_CAL: 'california\\groundshore4_cal',
    CARIBBEAN_GROUND_SHORELINE1_CRB: 'caribbean\\ground_shoreline1_crb',
    CARIBBEAN_GROUND_SHORELINE2_CRB: 'caribbean\\ground_shoreline2_crb',
    CARIBBEAN_GROUND_SHORELINE3_CRB: 'caribbean\\ground_shoreline3_crb',
    CAROLINAS_GROUND_SHORELINE1_CAR: 'carolinas\\ground_shoreline1_car',
    CAROLINAS_GROUND_SHORELINE2_CAR: 'carolinas\\ground_shoreline2_car',
    CAROLINAS_GROUND_SHORELINE3_CAR: 'carolinas\\ground_shoreline3_car',
    GREAT_LAKES_GROUND_SHORELINE1_GL: 'great_lakes\\ground_shoreline1_gl',
    GREAT_LAKES_GROUND_SHORELINE2_GL: 'great_lakes\\ground_shoreline2_gl',
    GREAT_LAKES_GROUND_SHORELINE3_GL: 'great_lakes\\ground_shoreline3_gl',
    NEW_ENGLAND_SHORELINE1_NE: 'new_england\\shoreline1_ne',
    NEW_ENGLAND_SHORELINE2_NE: 'new_england\\shoreline2_ne',
    NEW_ENGLAND_SHORELINE3_NE: 'new_england\\shoreline3_ne',
    NEW_ENGLAND_SHORELINE4_NE: 'new_england\\shoreline4_ne',
    NEW_ENGLAND_SHORELINE5_NE: 'new_england\\shoreline5_ne',
    NWTERRITORY_GROUND_SHORELINE4_NWT: 'nwterritory\\ground_shoreline4_nwt',
    PAMPAS_RIVER_SHORELINE1_PAM: 'pampas\\river_shoreline1_pam',
    PAMPAS_RIVER_SHORELINE2_PAM: 'pampas\\river_shoreline2_pam',
    PAMPAS_RIVER_SHORELINE3_PAM: 'pampas\\river_shoreline3_pam',
    PATAGONIA_GROUND_SHORELINE1_PAT: 'patagonia\\ground_shoreline1_pat',
    PATAGONIA_GROUND_SHORELINE2_PAT: 'patagonia\\ground_shoreline2_pat',
    PATAGONIA_GROUND_SHORELINE3_PAT: 'patagonia\\ground_shoreline3_pat',
    SAGUENAY_SHORELINE1_SAG: 'saguenay\\shoreline1_sag',
    SAGUENAY_SHORELINE2_SAG: 'saguenay\\shoreline2_sag',
    SAGUENAY_SHORELINE3_SAG: 'saguenay\\shoreline3_sag',
    YUCATAN_GROUND_SHORELINE1_YUC: 'yucatan\\ground_shoreline1_yuc',
    YUCATAN_GROUND_SHORELINE2_YUC: 'yucatan\\ground_shoreline2_yuc',
    YUCATAN_GROUND_SHORELINE3_YUC: 'yucatan\\ground_shoreline3_yuc',
    BAYOU_GROUND4_BAY: 'bayou\\ground4_bay',
    BAYOU_GROUND7_BAY: 'bayou\\ground7_bay',
    CARIBBEAN_GROUND5_CRB: 'caribbean\\ground5_crb',
    CITY_GROUND1_COB: 'city\\ground1_cob',
    AMAZON_GROUND_ROAD_SPC_AMA: 'amazon\\ground_road_spc_ama',
    CAROLINAS_GROUNDFORESTMARSH_CAR: 'carolinas\\groundforestmarsh_car',
    GREAT_LAKES_GROUND_ICE1_GL: 'great_lakes\\ground_ice1_gl',
    GREAT_LAKES_GROUND_ICE2_GL: 'great_lakes\\ground_ice2_gl',
    GREAT_LAKES_GROUND_ICE3_GL: 'great_lakes\\ground_ice3_gl',
    GREAT_PLAINS_GROUNDSPC_NONPASS_GP: 'great_plains\\groundSPC_nonpass_gp',
    YUKON_GROUND3_SPCNONBUILD_YUK: 'yukon\\ground3_SPCnonbuild_yuk',
    ROCKIESCLIFFTOP_ROC: 'rockiesclifftop_roc',
    BORNEO_GROUND_SAND1_BORNEO: 'borneo\\ground_sand1_borneo',
    BORNEO_GROUND_SAND2_BORNEO: 'borneo\\ground_sand2_borneo',
    BORNEO_GROUND_SAND3_BORNEO: 'borneo\\ground_sand3_borneo',
    BORNEO_GROUND_GRASS1_BORNEO: 'borneo\\ground_grass1_borneo',
    BORNEO_GROUND_GRASS2_BORNEO: 'borneo\\ground_grass2_borneo',
    BORNEO_GROUND_GRASS3_BORNEO: 'borneo\\ground_grass3_borneo',
    BORNEO_GROUND_GRASS4_BORNEO: 'borneo\\ground_grass4_borneo',
    BORNEO_GROUND_GRASS5_BORNEO: 'borneo\\ground_grass5_borneo',
    BORNEO_GROUND_FOREST_BORNEO: 'borneo\\ground_forest_borneo',
    CEYLON_GROUND_SAND2_CEYLON: 'ceylon\\ground_sand2_ceylon',
    CEYLON_GROUND_SAND3_CEYLON: 'ceylon\\ground_sand3_ceylon',
    CEYLON_GROUND_SAND4_CEYLON: 'ceylon\\ground_sand4_ceylon',
    CEYLON_GROUND_GRASS1_CEYLON: 'ceylon\\ground_grass1_ceylon',
    CEYLON_GROUND_GRASS2_CEYLON: 'ceylon\\ground_grass2_ceylon',
    CEYLON_GROUND_GRASS3_CEYLON: 'ceylon\\ground_grass3_ceylon',
    CEYLON_GROUND_GRASS4_CEYLON: 'ceylon\\ground_grass4_ceylon',
    CEYLON_SEAFLOOR0_CEYLON: 'ceylon\\seafloor0_ceylon',
    CEYLON_SEAFLOOR1_CEYLON: 'ceylon\\seafloor1_ceylon',
    CEYLON_SEAFLOOR2_CEYLON: 'ceylon\\seafloor2_ceylon',
    CEYLON_SEAFLOOR3_CEYLON: 'ceylon\\seafloor3_ceylon',
    CEYLON_SEAFLOOR4_CEYLON: 'ceylon\\seafloor4_ceylon',
    CEYLON_SEAFLOOR5_CEYLON: 'ceylon\\seafloor5_ceylon',
    CEYLON_CLIFFTOP_CEYLON: 'ceylon\\clifftop_ceylon',
    COASTAL_JAPAN_GROUND_DIRT1_CO_JAPAN: 'coastal_japan\\ground_dirt1_co_japan',
    COASTAL_JAPAN_GROUND_DIRT2_CO_JAPAN: 'coastal_japan\\ground_dirt2_co_japan',
    COASTAL_JAPAN_GROUND_DIRT3_CO_JAPAN: 'coastal_japan\\ground_dirt3_co_japan',
    COASTAL_JAPAN_GROUND_DIRT4_CO_JAPAN: 'coastal_japan\\ground_dirt4_co_japan',
    COASTAL_JAPAN_GROUND_GRASS1_CO_JAPAN: 'coastal_japan\\ground_grass1_co_japan',
    COASTAL_JAPAN_GROUND_GRASS2_CO_JAPAN: 'coastal_japan\\ground_grass2_co_japan',
    COASTAL_JAPAN_SEAFLOOR_CORAL1_CO_JAPAN: 'coastal_japan\\seafloor_coral1_co_japan',
    COASTAL_JAPAN_GROUND_GRASS3_CO_JAPAN: 'coastal_japan\\ground_grass3_co_japan',
    COASTAL_JAPAN_GROUND_FOREST_CO_JAPAN: 'coastal_japan\\ground_forest_co_japan',
    DECCAN_GROUND_DIRT2_DECCAN: 'deccan\\ground_dirt2_deccan',
    DECCAN_WALL_DECCAN: 'deccan\\wall_deccan',
    DECCAN_GROUND_GRASS1_DECCAN: 'deccan\\ground_grass1_deccan',
    DECCAN_GROUND_GRASS2_DECCAN: 'deccan\\ground_grass2_deccan',
    DECCAN_GROUND_GRASS3_DECCAN: 'deccan\\ground_grass3_deccan',
    DECCAN_GROUND_GRASS4_DECCAN: 'deccan\\ground_grass4_deccan',
    DECCAN_GROUND_DIRT3_DECCAN: 'deccan\\ground_dirt3_deccan',
    DECCAN_GROUND_DIRT4_DECCAN: 'deccan\\ground_dirt4_deccan',
    DECCAN_GROUND_DIRT5_DECCAN: 'deccan\\ground_dirt5_deccan',
    DECCAN_GROUND_FOREST_DECCAN: 'deccan\\ground_forest_deccan',
    HIMALAYAS_GROUND_DIRT1_HIMAL: 'himalayas\\ground_dirt1_himal',
    HIMALAYAS_GROUND_DIRT2_HIMAL: 'himalayas\\ground_dirt2_himal',
    HIMALAYAS_GROUND_DIRT3_HIMAL: 'himalayas\\ground_dirt3_himal',
    HIMALAYAS_GROUND_DIRT4_HIMAL: 'himalayas\\ground_dirt4_himal',
    HIMALAYAS_GROUND_DIRT5_HIMAL: 'himalayas\\ground_dirt5_himal',
    HIMALAYAS_GROUND_DIRT6_HIMAL: 'himalayas\\ground_dirt6_himal',
    HIMALAYAS_GROUND_DIRT7_HIMAL: 'himalayas\\ground_dirt7_himal',
    HIMALAYAS_GROUND_DIRT8_HIMAL: 'himalayas\\ground_dirt8_himal',
    HIMALAYAS_CLIFF_HIMAL_EDGE: 'himalayas\\cliff_himal_edge',
    HIMALAYAS_CLIFF_HIMAL_TOP: 'himalayas\\cliff_himal_top',
    MONGOLIA_GROUND_FOREST_MONGOL: 'mongolia\\ground_forest_mongol',
    MONGOLIA_GROUND_GRASS1_MONGOL: 'mongolia\\ground_grass1_mongol',
    MONGOLIA_GROUND_GRASS2_MONGOL: 'mongolia\\ground_grass2_mongol',
    MONGOLIA_GROUND_GRASS3_MONGOL: 'mongolia\\ground_grass3_mongol',
    MONGOLIA_GROUND_GRASS4_MONGOL: 'mongolia\\ground_grass4_mongol',
    MONGOLIA_GROUND_GRASS5_MONGOL: 'mongolia\\ground_grass5_mongol',
    MONGOLIA_GROUND_GRASS6_MONGOL: 'mongolia\\ground_grass6_mongol',
    MONGOLIA_GROUND_SAND1_MONGOL: 'mongolia\\ground_sand1_mongol',
    MONGOLIA_GROUND_SAND2_MONGOL: 'mongolia\\ground_sand2_mongol',
    MONGOLIA_GROUND_SAND3_MONGOL: 'mongolia\\ground_sand3_mongol',
    YELLOW_RIVER_FOREST_YELLOW_RIV: 'yellow_river\\forest_yellow_riv',
    YELLOW_RIVER_GRASS1_YELLOW_RIV: 'yellow_river\\grass1_yellow_riv',
    YELLOW_RIVER_GRASS2_YELLOW_RIV: 'yellow_river\\grass2_yellow_riv',
    YELLOW_RIVER_GRASS3_YELLOW_RIV: 'yellow_river\\grass3_yellow_riv',
    YELLOW_RIVER_GRASS4_YELLOW_RIV: 'yellow_river\\grass4_yellow_riv',
    YELLOW_RIVER_STONE1_YELLOW_RIV: 'yellow_river\\stone1_yellow_riv',
    YELLOW_RIVER_STONE2_YELLOW_RIV: 'yellow_river\\stone2_yellow_riv',
    YELLOW_RIVER_STONE3_YELLOW_RIV: 'yellow_river\\stone3_yellow_riv',
    BORNEO_SHORELINE1_BORNEO: 'borneo\\shoreline1_borneo',
    BORNEO_SEAFLOOR1_BORNEO: 'borneo\\seafloor1_borneo',
    CEYLON_GROUND_SHORELINE1_CEYLON: 'ceylon\\ground_shoreline1_ceylon',
    CEYLON_GROUND_SHORELINE2_CEYLON: 'ceylon\\ground_shoreline2_ceylon',
    COASTAL_JAPAN_SHORELINE1_CO_JAPAN: 'coastal_japan\\shoreline1_co_japan',
    YELLOW_RIVER_SHORELINE1_YELLOW_RIV: 'yellow_river\\shoreline1_yellow_riv',
    CEYLON_GROUND_SAND1_CEYLON: 'ceylon\\ground_sand1_ceylon',

    //  water
    ATLANTIC_COAST: 'atlantic coast',
    CARIBBEAN_COAST: 'caribbean coast',
    CINEMATIC_SHIP_OCEAN: 'cinematic ship ocean',
    HUDSON_BAY: 'hudson bay',
    BAYOU_SPC: 'bayou spc',
    NEW_ENGLAND_COAST: 'new england coast',
    YUCATAN_COAST: 'yucatan coast',
    GREAT_LAKES_ICE: 'great lakes ice',
    GREAT_LAKES: 'great lakes',
    GREAT_PLAINS_POND: 'great plains pond',
    TEXAS_POND: 'texas pond',
    NEW_ENGLAND_LAKE: 'new england lake',
    SAGUENAY_LAKE: 'saguenay lake',
    BAYOU: 'bayou',
    AMSTERDAM: 'amsterdam',
    PARIS: 'paris',
    BERLIN: 'berlin',
    LISON: 'lisbon',
    LONDON: 'london',
    SEVILLE: 'seville',
    CONSTANTINOPLE: 'constantinople',
    IROQUOIS_HC: 'iroquois_hc',
    NORTHWEST_TERRITORY_WATER: 'northwest territory water',
    CALIFORNIA_COAST: 'california coast',
    ARAUCANIA_NORTH_COAST: 'araucania north coast',
    ARAUCANIA_CENTRAL_COAST: 'araucania central coast',
    ARAUCANIA_SOUTHERN_COAST: 'araucania southern coast',
    BORNEO_COAST: 'borneo coast',
    CEYLON_COAST: 'ceylon coast',
    COASTAL_JAPAN: 'coastal japan',
    BORNEO_WATER: 'borneo water',
    CHINA_HC: 'china_hc',
    INDIA_HC: 'india_hc',
    YELLOW_RIVER_FLOODED: 'yellow river flooded',

    // cliff
    ANDES: 'andes',
    CALIFORNIA: 'california',
    DECCAN_PLATEAU: 'deccan plateau',
    NEW_ENGLAND: 'new england',
    ARAUCANIA_CENTRAL: 'araucania central',
    PAINTEDDESERT: 'painteddesert',
    PATAGONIA: 'patagonia',
    ROCKY_MOUNTAIN_EDGE: 'rocky mountain edge',
    ROCKY_MOUNTAIN2: 'rocky mountain2',
    SONORA: 'sonora',
    TEXAS: 'texas',
    TEXAS_GRASS: 'texas grass',
    ARAUCANIA_SOUTH: 'araucania south',
    NEW_ENGLAND_INLAND_GRASS: 'new england inland grass',
    ARAUCANIA_NORTH_COAST: 'araucania north coase',
};

module.exports = {
    identifierMapper,
    getTypeOf,
    listOfFunctionWithUUID,
    getTypeOfReturnedValue,
    generateXml,
};
